# image: https://github.com/bitnami/bitnami-docker-mediawiki

version: '3.8'

services:
  mediawiki:
    image: $APP_REPO:$APP_VERSION
    container_name: $APP_NAME
    ports:
      - ${APP_HTTP_PORT}:8080
    environment:
      - MEDIAWIKI_DATABASE_HOST=db
      - MEDIAWIKI_DATABASE_PORT_NUMBER=$DB_MYSQL_PORT
      - MEDIAWIKI_DATABASE_USER=$DB_MYSQL_USER
      - MEDIAWIKI_DATABASE_NAME=$DB_MYSQL_NAME
      - MEDIAWIKI_DATABASE_PASSWORD=$DB_MYSQL_PASSWORD
      - MEDIAWIKI_USERNAME=$APP_USER
      - MEDIAWIKI_PASSWORD=$APP_PASSWORD
      - MEDIAWIKI_EMAIL=$APP_EMAIL
      - MEDIAWIKI_HOST=$APP_URL
      - MEDIAWIKI_WIKI_NAME=$APP_SITENAME
      - PHP_MEMORY_LIMIT=512M
    volumes:
      - mediawiki:/bitnami/mediawiki
    depends_on:
      - db
    restart: always

  db:
    image: mysql:$DB_MYSQL_VERSION
    container_name: $APP_NAME-db
    restart: always
    #ports:
    # - $DB_MYSQL_PORT:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $DB_MYSQL_NAME
      MYSQL_USER: $DB_MYSQL_USER
      MYSQL_PASSWORD: $DB_MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_MYSQL_PASSWORD

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  mediawiki:
  mysql:
